import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { DamageScalingType, SkillEffectType } from "@/modules/skills/enums/skill.enum.js";
import type { Skill } from "@/modules/skills/entities/skill.entity.js";
import { SkillRepo } from "@/modules/skills/repositories/skill.repository.js";
import { sortSkillHitEvents } from "@/modules/skills/services/skill.service.js";
import { getSkillDurationTicks } from "@/rooms/world/utils/skill-attack.world.util.js";
import { WORLD_TICK_RATE, skillEventTicks } from "@/rooms/world/utils/tick.world.util.js";

/**
 * Xuất skill đang bật trong DB ra `<outputDir>/skills.json` cho client — client không giữ bản copy
 * tay nào. Mọi giá trị đã quy đổi sẵn theo đúng cách server dùng (tick mô phỏng, thời lượng đòn,
 * hệ số damage), nên client chỉ việc đọc, không tự tính lại.
 *
 * `outputDir` là thư mục `Resources/Config` của project Unity, truyền từ script trong package.json
 * (`seed`, `config:export`); thư mục cha không tồn tại (vd. chạy seed trên server deploy) thì bỏ qua.
 */
export async function exportClientConfig(outputDir: string): Promise<void> {
    const directory = resolve(outputDir);
    if (!existsSync(dirname(directory))) {
        console.info(`⏭️  [ClientConfig] ${directory} not found — skipped`);
        return;
    }

    const skills = await SkillRepo.findEnabled();
    const config = {
        comment:
            "Generated by ERPG-server (yarn config:export) from the skills table. Do not edit.",
        tickRate: WORLD_TICK_RATE,
        skills: skills.map(toClientSkill),
    };

    mkdirSync(directory, { recursive: true });
    const file = join(directory, "skills.json");
    writeFileSync(file, `${JSON.stringify(config, null, 4)}\n`, "utf8");
    console.info(`✅ [ClientConfig] ${skills.length} skills -> ${file}`);
}

function toClientSkill(skill: Skill) {
    return {
        id: skill.id,
        code: skill.code,
        skillType: skill.skillType,
        castRange: skill.castRange,
        cooldownMs: skill.cooldownMs,
        /** Số tick mô phỏng của cả đòn (khoá di chuyển) — giống PlayerAttackChain. */
        durationTicks: getSkillDurationTicks(skill, WORLD_TICK_RATE),
        hitEvents: sortSkillHitEvents(skill.skillHitEvents).map((event) => {
            const damageEffects = event.effects.filter(
                (effect) => effect.effectType === SkillEffectType.DAMAGE
            );
            return {
                /** Tick mô phỏng (WORLD_TICK_RATE) tính từ lúc bắt đầu đòn. */
                triggerTicks: skillEventTicks(event.triggerTicks, WORLD_TICK_RATE),
                shape: event.shape,
                range: event.range,
                width: event.width,
                height: event.height,
                radius: event.radius,
                angle: event.angle,
                offsetX: event.offsetX,
                offsetY: event.offsetY,
                /** damage = damageBase + attack × damageAttackScaling (như getSkillHitDamage). */
                damageBase: damageEffects.reduce((total, effect) => total + effect.baseValue, 0),
                damageAttackScaling: damageEffects
                    .filter((effect) => effect.scalingType === DamageScalingType.ATTACK)
                    .reduce((total, effect) => total + effect.scalingValue, 0),
            };
        }),
    };
}
