import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { DialogueRepo } from "@/modules/dialogues/repositories/dialogue.repository.js";
import { loadMapFiles } from "@/modules/maps/seeds/game-map.seed.js";
import { NpcRepo } from "@/modules/npcs/repositories/npc.repository.js";
import { QuestRepo } from "@/modules/quests/repositories/quest.repository.js";
import { collectLocaleKeys } from "@/modules/quests/utils/locale-keys.util.js";
import {
    DamageScalingType,
    HitDelivery,
    SkillEffectType,
} from "@/modules/skills/enums/skill.enum.js";
import type { Skill } from "@/modules/skills/entities/skill.entity.js";
import { SkillRepo } from "@/modules/skills/repositories/skill.repository.js";
import { sortSkillHitEvents } from "@/modules/skills/services/skill.service.js";
import { getSkillDurationTicks } from "@/rooms/world/utils/skill-attack.world.util.js";
import {
    WORLD_TICK_RATE,
    millisecondsToTicks,
    skillEventTicks,
} from "@/rooms/world/utils/tick.world.util.js";

/**
 * Xuất skill đang bật trong DB ra `<outputDir>/skills.json` cho client — client không giữ bản copy
 * tay nào. Mọi giá trị đã quy đổi sẵn theo đúng cách server dùng (tick mô phỏng, thời lượng đòn,
 * hệ số damage), nên client chỉ việc đọc, không tự tính lại.
 *
 * `outputDir` là thư mục `Resources/Config` của project Unity, truyền từ script trong package.json
 * (`seed`, `config:export`); thư mục cha không tồn tại (vd. chạy seed trên server deploy) thì bỏ qua.
 */
export async function exportClientConfig(outputDir: string): Promise<void> {
    const directory = resolve(outputDir);
    if (!existsSync(dirname(directory))) {
        console.info(`⏭️  [ClientConfig] ${directory} not found — skipped`);
        return;
    }

    const skills = await SkillRepo.findEnabled();
    const config = {
        comment:
            "Generated by ERPG-server (yarn config:export) from the skills table. Do not edit.",
        tickRate: WORLD_TICK_RATE,
        skills: skills.map(toClientSkill),
    };

    mkdirSync(directory, { recursive: true });
    const file = join(directory, "skills.json");
    writeFileSync(file, `${JSON.stringify(config, null, 4)}\n`, "utf8");
    console.info(`✅ [ClientConfig] ${skills.length} skills -> ${file}`);

    await exportContentConfig(directory);
}

/**
 * `content.json` (NPC, thoại, quest) + `locale-keys.json` (mọi key cần dịch). Layout map không xuất ở đây:
 * map do Unity export ra file `.map.json` nên client đã có sẵn.
 */
async function exportContentConfig(directory: string): Promise<void> {
    const [npcs, dialogues, quests] = await Promise.all([
        NpcRepo.findEnabled(),
        DialogueRepo.findEnabled(),
        QuestRepo.findEnabled(),
    ]);
    const content = {
        comment: "Generated by ERPG-server (yarn config:export). Do not edit.",
        npcs: npcs.map(({ code, colliderWidth, colliderHeight, interactRadius, functions }) => ({
            code,
            colliderWidth,
            colliderHeight,
            interactRadius,
            functions,
        })),
        dialogues: dialogues.map(({ code, nodes }) => ({ code, nodes })),
        quests: quests.map((quest) => ({
            code: quest.code,
            requiredLevel: quest.requiredLevel,
            giverNpcCode: quest.giverNpcCode,
            turnInNpcCode: quest.turnInNpcCode,
            repeat: quest.repeat,
            objectives: quest.objectives,
            rewards: quest.rewards,
        })),
    };
    const keys = collectLocaleKeys({ maps: loadMapFiles(), npcs, dialogues, quests });
    writeFileSync(
        join(directory, "content.json"),
        `${JSON.stringify(content, null, 4)}
`,
        "utf8"
    );
    writeFileSync(
        join(directory, "locale-keys.json"),
        `${JSON.stringify(keys, null, 4)}
`,
        "utf8"
    );
    console.info(
        `✅ [ClientConfig] ${npcs.length} npcs, ${dialogues.length} dialogues, ${quests.length} quests, ${keys.length} locale keys`
    );
}

function toClientSkill(skill: Skill) {
    return {
        id: skill.id,
        code: skill.code,
        skillType: skill.skillType,
        castRange: skill.castRange,
        cooldownMs: skill.cooldownMs,
        /** Thuộc combo đánh thường (theo thứ tự trong `skills` của player/monster). */
        basicAttack: skill.basicAttack,
        /** Số tick mô phỏng của cả đòn (khoá di chuyển) — giống PlayerAttackChain. */
        durationTicks: getSkillDurationTicks(skill, WORLD_TICK_RATE),
        hitEvents: sortSkillHitEvents(skill.skillHitEvents).map((event) => {
            const damageEffects = event.effects.filter(
                (effect) => effect.effectType === SkillEffectType.DAMAGE
            );
            return {
                /** Tick mô phỏng (WORLD_TICK_RATE) tính từ lúc bắt đầu đòn. */
                triggerTicks: skillEventTicks(event.triggerTicks, WORLD_TICK_RATE),
                shape: event.shape,
                range: event.range,
                width: event.width,
                height: event.height,
                radius: event.radius,
                angle: event.angle,
                offsetX: event.offsetX,
                offsetY: event.offsetY,
                /** Damage gốc để client predict: damageBase + attack × damageAttackScaling (server tính đủ qua `calculateDamage`). */
                damageBase: damageEffects.reduce((total, effect) => total + effect.baseValue, 0),
                damageAttackScaling: damageEffects
                    .filter((effect) => effect.scalingType === DamageScalingType.ATTACK)
                    .reduce((total, effect) => total + effect.scalingValue, 0),
                /** HITBOX / PROJECTILE / AREA — xem SkillDeliveryWorldService. */
                delivery: event.delivery ?? HitDelivery.HITBOX,
                projectile: event.projectile
                    ? {
                          speed: event.projectile.speed,
                          maxDistance: event.projectile.maxDistance,
                          radius: event.projectile.radius,
                          hitBehavior: event.projectile.hitBehavior,
                          maxHits: event.projectile.maxHits,
                      }
                    : null,
                area: event.area
                    ? {
                          /** Tick mô phỏng từ lúc đặt vùng tới lúc gây damage (0 = ngay). */
                          delayTicks:
                              event.area.delayMs > 0
                                  ? millisecondsToTicks(event.area.delayMs, WORLD_TICK_RATE)
                                  : 0,
                          untargetedDistance: event.area.untargetedDistance,
                      }
                    : null,
            };
        }),
    };
}
