export enum ResponseCode {
    // Common
    NOT_FOUND = "NOT_FOUND",
    INVALID_INPUT = "INVALID_INPUT",
    MISSING_TOKEN = "MISSING_TOKEN",
    INVALID_TOKEN = "INVALID_TOKEN",
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",

    // Client
    CLIENT_OUTDATED = "CLIENT_OUTDATED",
    CLIENT_PLATFORM_DISABLED = "CLIENT_PLATFORM_DISABLED",

    // Auth
    AUTH_EMAIL_EXISTS = "AUTH_EMAIL_EXISTS",
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
    AUTH_ACCOUNT_BANNED = "AUTH_ACCOUNT_BANNED",
    AUTH_ACCOUNT_INACTIVE = "AUTH_ACCOUNT_INACTIVE",
    AUTH_SESSION_NOT_FOUND = "AUTH_SESSION_NOT_FOUND",
    AUTH_ACCOUNT_DELETED = "AUTH_ACCOUNT_DELETED",

    // Account deletion
    ACCOUNT_DELETION_REQUEST_NOT_FOUND = "ACCOUNT_DELETION_REQUEST_NOT_FOUND",
    ACCOUNT_DELETION_REQUEST_PROCESSED = "ACCOUNT_DELETION_REQUEST_PROCESSED",

    // OAuth
    OAUTH_PROVIDER_DISABLED = "OAUTH_PROVIDER_DISABLED",
    OAUTH_INVALID_CREDENTIAL = "OAUTH_INVALID_CREDENTIAL",
    OAUTH_PROVIDER_ERROR = "OAUTH_PROVIDER_ERROR",

    // Admin
    ADMIN_INVALID_CREDENTIALS = "ADMIN_INVALID_CREDENTIALS",
    ADMIN_ACCESS_REQUIRED = "ADMIN_ACCESS_REQUIRED",

    // Game Server
    GAME_SERVER_CODE_EXISTS = "GAME_SERVER_CODE_EXISTS",
    GAME_SERVER_UNAVAILABLE = "GAME_SERVER_UNAVAILABLE",

    // Map
    MAP_CODE_EXISTS = "MAP_CODE_EXISTS",
    MAP_NOT_FOUND = "MAP_NOT_FOUND",

    // Content (NPC, dialogue, quest)
    NPC_CODE_EXISTS = "NPC_CODE_EXISTS",
    DIALOGUE_CODE_EXISTS = "DIALOGUE_CODE_EXISTS",
    DIALOGUE_INVALID = "DIALOGUE_INVALID",
    QUEST_CODE_EXISTS = "QUEST_CODE_EXISTS",

    // Player
    PLAYER_NAME_EXISTS = "PLAYER_NAME_EXISTS",
    PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
    PLAYER_BANNED = "PLAYER_BANNED",
    PLAYER_ALREADY_EXISTS = "PLAYER_ALREADY_EXISTS",
    PLAYER_LIMIT_REACHED = "PLAYER_LIMIT_REACHED",
    PLAYER_NAME_INVALID = "PLAYER_NAME_INVALID",

    // Class
    CLASS_NOT_AVAILABLE = "CLASS_NOT_AVAILABLE",

    // Master data
    MASTER_DATA_NOT_FOUND = "MASTER_DATA_NOT_FOUND",
}
